server:
  port: 8081

spring:
  application:
    name: registration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/project
